### ISSUE TITLE
MomentoError::NotFound does not provide a useful message for Display

### ISSUE THREAD

**Issue by brayniac** [momentohq/client-sdk-rust#141]
The `MomentoError::NotFound` variant produces the string `not found: not found`. It seems it would be more helpful if it mentions that the cache was not found. Otherwise this error messaging is confusing, particularly in response to a `get` request.

**Comment by nand4011** [comment]
Closing this in favor of a more general issue to bring the error messages in line with the JavaScript errors: https://github.com/momentohq/client-sdk-rust/issues/171
