### ISSUE TITLE
Add unimplemented list cache methods

### ISSUE THREAD

**Issue by nand4011** [momentohq/client-sdk-rust#165]
The Rust SDK currently does not support these list methods:

- listConcatenateBack
- listConcatenateFront
- listRetain

**Comment by anitarua** [comment]
New methods:

- listConcatenateBack
- listConcatenateFront
- listRetain

Port from `simple_cache_client` to `cache_client`:

- listFetch
- listLength
- listPopBack
- listPopFront
- listPushBack
- listPushFront
- listRemoveValue
