### ISSUE TITLE
Add unimplemented dictionary cache methods

### ISSUE THREAD

**Issue by nand4011** [momentohq/client-sdk-rust#166]
The Rust SDK does not support the following dictionary cache methods:

- dictionaryFetch
- dictionaryLength
- dictionaryGetField
- dictionaryGetFields
- dictionaryRemoveField
- dictionaryRemoveFields
- dictionarySetField
- dictionarySetFields
- dictionaryIncrement

**Comment by malandis** [comment]
Implemented:
- dictionaryFetch
- dictionaryLength
- dictionaryGetFields
- dictionaryRemoveFields
- dictionarySetFields

Adding the unimplemented methods to the backlog:
- dictionaryIncrement
- dictionarySetField
- dictionaryRemoveField
- dictionaryGetField
