### ISSUE TITLE
Add sorted set cache methods

### ISSUE THREAD

**Issue by nand4011** [momentohq/client-sdk-rust#168]
The Rust SDK does not support the following sorted set cache methods:

- ~~sortedSetFetchByRank~~
- ~~sortedSetFetchByScore~~
- sortedSetLength
- sortedSetLengthByScore
- sortedSetGetScores
- sortedSetIncrementScore
- ~~sortedSetPutElement~~
- ~~sortedSetPutElements~~
- sortedSetRemoveElement
- sortedSetRemoveElements

The sorted set fetch logic also needs to be updated, as per https://github.com/momentohq/client-sdk-rust/issues/135

**Comment by anitarua** [comment]
To round out the sorted set methods and close this ticket, I'll implement:

- length
- get rank
- get score
- remove elements
