### ISSUE TITLE
Ensure that error messages are descriptive

### ISSUE THREAD

**Issue by nand4011** [momentohq/client-sdk-rust#171]
Error messages should be as descriptive as the error messages in the JavaScript SDK: https://github.com/momentohq/client-sdk-javascript/blob/main/packages/core/src/errors/errors.ts

**Comment by cprice404** [comment]
I haven't looked over the code for the errors in the Rust SDK yet but I would take this description a step further and say that we should try to make sure that the errors are modeled as closely as possible to the ones in the other SDKs. So we should make sure the list of error types in the enum / class hierarchy matches, make sure the messages are consistent, make sure we have properties for the errorCode / innerError, etc.
