### ISSUE TITLE
Decide on default arguments for sorted set fetch by rank and score

### ISSUE THREAD

**Issue by nand4011** [momentohq/client-sdk-rust#192]
The sorted_set_fetch_by_rank and sorted_set_fetch_by_score functions in the new cache client both take cache name, sorted set name, and sort order, and they both return the same response object. i.e. they are the same function. We need to figure out which additional arguments we should add to either of them to separate them.
Idea:
sorted_set_fetch that takes cache name, sorted set name, sort order, limit, offset
sorted_set_fetch_by_rank that takes cache name, sorted set name, sort order, start_rank, end_rank
sorted_set_fetch_by_score that takes cache name, sorted set name, sort order, min_score, max_score

**Comment by anitarua** [comment]
Not actually sure if any action needs to be taken here. Fetch by score and rank appear to have optional arguments in all the SDKs they're implemented in:

* JS fetch by [rank](https://github.com/momentohq/client-sdk-javascript/blob/main/packages/core/src/internal/clients/cache/AbstractCacheClient.ts#L1255) and [score](https://github.com/momentohq/client-sdk-javascript/blob/main/packages/core/src/internal/clients/cache/AbstractCacheClient.ts#L1293)
* Python fetch by [rank](https://github.com/momentohq/client-sdk-python/blob/79bc60ef75ea098112403f91b11f2b221be58b14/src/momento/cache_client.py#L927) and [score](https://github.com/momentohq/client-sdk-python/blob/79bc60ef75ea098112403f91b11f2b221be58b14/src/momento/cache_client.py#L894)
* Java fetch by [rank](https://github.com/momentohq/client-sdk-java/blob/660519a415a18ef2b0b1ca798231abbcc042cc65/momento-sdk/src/main/java/momento/sdk/CacheClient.java#L1036) and [score](https://github.com/momentohq/client-sdk-java/blob/660519a415a18ef2b0b1ca798231abbcc042cc65/momento-sdk/src/main/java/momento/sdk/CacheClient.java#L1077)
* Go fetch by [rank](https://github.com/momentohq/client-sdk-go/blob/7858197b97c4574407c5eb9caa013bc389760975/momento/sorted_set_fetch_by_rank.go#L11) and [score](https://github.com/momentohq/client-sdk-go/blob/7858197b97c4574407c5eb9caa013bc389760975/momento/sorted_set_fetch_by_score.go#L11)
* Elixir fetch by [rank](https://github.com/momentohq/client-sdk-elixir/blob/84e4d1856753a7d183a1ad0d6e886dd34d762eeb/src/lib/momento/internal/scs_data_client.ex#L203) and [score](https://github.com/momentohq/client-sdk-elixir/blob/84e4d1856753a7d183a1ad0d6e886dd34d762eeb/src/lib/momento/internal/scs_data_client.ex#L288)

**Comment by anitarua** [comment]
During meeting, decided to:
* Not change the fetch by score API, docs should point to using the request builder since there are so many optional args that can be used in any combination that works for the user
* Include start and end rank as part of the fetch by rank API as it seems likely users will use that API to page through their sorted set
