### ISSUE TITLE
tests sometimes take 6 hours to fail?

### ISSUE THREAD

**Issue by anitarua** [momentohq/client-sdk-rust#205]
So far seen once instance of 3 sorted set tests that took 6 hours before they failed: https://github.com/momentohq/client-sdk-rust/actions/runs/8427411620/job/23077905848 

```
running 8 tests
test sorted_set_fetch_by_rank_happy_path has been running for over 60 seconds
test sorted_set_fetch_by_rank_nonexistent_cache has been running for over 60 seconds
test sorted_set_fetch_by_score_happy_path has been running for over 60 seconds
Error: The operation was canceled.
```

Not sure why this happened, but if this keeps occurring, we could try adding a [timeout macro](https://docs.rs/ntest/0.7.2/ntest/attr.timeout.html) to the problematic tests

**Comment by malandis** [comment]
@anitarua Does this still happen?

**Comment by anitarua** [comment]
Haven't seen it happen since so this can probably be closed
