### ISSUE TITLE
Revise model for response types?

### ISSUE THREAD

**Issue by anitarua** [momentohq/client-sdk-rust#285]
After discussing, we're going to go ahead and rename response types to include `Response` at the end.

----------

cc: @cprice404 @malandis 

Chris: for response types that only have a single non-error case, like TopicPublish and DictionarySetFields, I can’t decide how I feel about our current representation. I like that we have a struct for these cases, in case we need to add fields in the future like fieldCount or any other metadata. But right now it feels like I can’t access that struct without a match, and that match feels confusing and superfluous. I suspect that the argument in favor of this is to make it symmetrical with the response types that have more than one success case, like Hit/ Miss, but after typing some code against this SDK it felt so weird to have to put that match there that I kind of don’t think the symmetry is a net win. I think this is a place where, in languages like Rust/Golang that have a formal built-in pattern for returning errors along with a return value, we will likely just want to shed the outer type for a Success response and avoid forcing people to do an extra match. This might warrant a quick discussion with some interested parties to get aligned if there is not an obvious consensus.

Kenny:
this completion is hard to guess which one is right
![Untitled](https://github.com/momentohq/client-sdk-rust/assets/138700973/1cc91047-bd62-4c0f-9797-8a0088a6307c)

Can rename them to `*Response` ? Or might be helped by removing structs for non-error cases

**Comment by malandis** [comment]
> But right now it feels like I can’t access that struct without a match, and that match feels confusing and superfluous.

I am unclear what is meant here. When using the ?-operator I get the struct back:
![image](https://github.com/momentohq/client-sdk-rust/assets/3690240/1b8de4f9-1d64-46df-9f84-36ba2a260a67)

And if doing a match over the `Result` we can ignore it if needed
![image](https://github.com/momentohq/client-sdk-rust/assets/3690240/4847fe60-be7b-4f8f-8db6-d9dfa57a318f)

Let's sync up about this @cprice404 

re @kvcache:
> this completion is hard to guess which one is right

I agree. I feel like the `momento::cache` mod is cluttered. I also feel like constructing a request will be uncommon, so placing all request types in a new mod, eg `momento::cache::requests` and not rolling them up to `momento::cache` would help.

**Comment by malandis** [comment]
# Re: @cprice404 's feedback

After some digging, we could not reproduce Chris' feedback and he has withdrawn it. No further action needed here.

# Re: @kvcache 's feedback about the response type names

After discussion with @anitarua and @cprice404 , we have decided to append the noun `Response` to each of the response types. While this will make the names longer, IDEs will generate these in match expressions, so we won't be forcing developers into making more effort to type the names.
