### ISSUE TITLE
what to do about discontinuities

### ISSUE THREAD

**Issue by cprice404** [momentohq/client-sdk-rust#299]

**Comment by anitarua** [comment]
We discussed with Kenny and determined we'll eventually have two subscribe methods:
* The basic `subscribe` method will return only values (string or binary), meaning we can remove the `Discontinuity` type and a pattern matching layer from the Rust SDK for now
* The advanced method (to be named) that will return `SubscriptionItem`s that include values, discontinuities, heartbeats, etc future messages we want to return
