### ISSUE TITLE
Add support for SetIfNotExists

### ISSUE THREAD

**Issue by rlinehan** [momentohq/client-sdk-rust#79]
`SetIfNotExists` is a new API that stores a value for a key if the key is not already present (and returns `Stored` along with the key and value), otherwise it does not store the value (and returns `NotStored`).

Although it's not really to do with "data structures," this API is only available in caches that also support data structures.

**Comment by nand4011** [comment]
Closing in favor of a general ticket to implement the missing scalar methods: https://github.com/momentohq/client-sdk-rust/issues/164
